name: Release on Pushing Tag

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Set execute permission for build.sh
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: List files in the build directory
        run: ls -la build

      - name: List files in the exported directory
        run: ls -la build/exported

      - name: Rename exported ipa file
        run: | 
          TAG="${GITHUB_REF##*/}"
          TAG_NUM="${TAG#v}"
          echo "APP_NAME=NuitComic-$TAG_NUM-ios.ipa" >> $GITHUB_ENV
          mv build/exported/NuitComic.ipa build/exported/$APP_NAME

      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/exportted/$APP_NAME
          draft: true

      
          


